apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-website
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-website
  template:
    metadata:
      labels:
        app: react-website
    spec:
      containers:
        - name: react-website
          image: jarnbjorn92/react-website:latest 
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
