apiVersion: v1
kind: Service
metadata:
  name: react-website
  namespace: default
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: react-website
