name: Deploy to Production

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/personal-website-v2:latest

    - name: Create kubeconfig
      run: |
        mkdir -p ${HOME}/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > ${HOME}/.kube/config
        chmod 600 ${HOME}/.kube/config
      
    - name: Deploy to Kubernetes
      run: |
        kubectl create namespace personal-website --dry-run=client -o yaml | kubectl apply -f -
        kubectl apply -f k8s/deployment.yaml -n personal-website
        kubectl rollout status deployment/personal-website -n personal-website
